version: '3.8'

services:
  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    restart: always
    environment:
      - DD_API_KEY=a6a0eec0e8228f6091eb296a563a2c31 
      - DD_SITE=datadoghq.com
      - DD_DOCKER_ENV=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=false
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - datadog-network

networks:
  datadog-network:
    driver: bridge
